export const ROUTES = {
  home: "/",
  login: "/login",
  signup: "/signup",
  signupHost: "/signup/host",
  dashboard: "/dashboard",
  profile: "/me",
  settings: "/settings",
  createListing: "/listings/new",
  viewLocations: "/locations",
  manageListings: "/listings",
  manageReservations: "/reservations",
  editListings: "/listings/edit",
  uploadProfileImg: "/upload-profile-image",
  reservations: "/reservations",
};
